<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFrgr5Nx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFrgr5Nx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFrgr5Nx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFrgr5Nx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFrgr5Nx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Frgr5Nx',
    'container.build_id' => '7626a542',
    'container.build_time' => 1563198786,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFrgr5Nx');
