<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerARxrjcQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerARxrjcQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerARxrjcQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerARxrjcQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerARxrjcQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ARxrjcQ',
    'container.build_id' => '04f4df02',
    'container.build_time' => 1563200685,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerARxrjcQ');
